import type { Metadata } from "next";
import { ConceptRender, OwnerTag, PageFrame, PageHero } from "../components";

export const metadata: Metadata = { title: "About", description: "Verified company-record details and owner-review biography placeholders for Gregory General Contractors." };

const ownerSections = ["Juan’s owner-approved biography and public name", "Why the company was started", "Current team names and roles", "Types of projects the company values", "Construction philosophy", "Communication approach", "Experience coordinating permits and trades", "Confirmed Oregon service area", "Company milestones"];

export default function AboutPage() {
  return <PageFrame>
    <PageHero eyebrow="About" title="A company profile built on records, not assumptions." image={{src: "/concepts/pnw-home-renovation.webp", alt: "Illustrative 3D render of a renovated Pacific Northwest residence", uploadLabel: "Authentic Gregory project or company image for the About page"}}><p>Gregory General Contractors, Inc. is a residential general contractor based in Wilsonville, Oregon. The corporation was registered in Oregon in 2003 and first received its current Oregon CCB license in 2004.</p></PageHero>
    <section className="section"><div className="shell split-grid"><ConceptRender src="/concepts/jobsite-planning-v2.webp" alt="AI-generated illustrative image of construction professionals reviewing plans at a residential jobsite" uploadLabel="Professional portrait of Juan Ramirez Estrada or an owner-approved Gregory team photograph at a jobsite" /><div><p className="eyebrow">Owner profile</p><h2>Name and biography pending approval.</h2><OwnerTag>Confirm public name: Juan Ramirez Estrada or Juan Manuel Ramirez Estrada</OwnerTag><OwnerTag>Confirm title: Owner, President, General Contractor, Project Manager or another approved title</OwnerTag><p>No childhood, immigration, education, apprenticeship, family or personal history has been invented. The name “Gregory” is not presented as an owner surname.</p></div></div></section>
    <section className="section section-alt"><div className="shell"><p className="eyebrow">Owner-editable company story</p><h2>Information needed to complete this page.</h2><div className="card-grid">{ownerSections.map((title) => <article className="content-card" key={title}><div className="card-body"><OwnerTag>Owner content required</OwnerTag><h3>{title}</h3><p>Use specific, factual, owner-approved copy here before publication.</p></div></article>)}</div></div></section>
    <section className="section"><div className="shell visual-story-grid"><ConceptRender src="/concepts/addition-structural.webp" alt="Illustrative 3D render of a framed residential addition" uploadLabel="Current Gregory crew or in-progress project photograph with permission" /><ConceptRender src="/concepts/deck-concrete.webp" alt="Illustrative 3D render of a rebuilt cedar deck and stair" uploadLabel="Company vehicle, jobsite sign, branded equipment or completed exterior project photograph" /></div></section>
  </PageFrame>;
}
